### ISSUE TITLE
Stork pods in CrashloopBackOff

### ISSUE THREAD

**Issue by adityadani** [libopenstorage/stork#45]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Yes

**What happened**:
All stork pods are in CrashloopBackOff. The logs show that there is a panic in stork.

```
I0317 22:00:39.137524       1 snapshot-controller.go:169] Starting snapshot controller
I0317 22:00:39.137558       1 controller_utils.go:1041] Waiting for caches to sync for snapshot-controller controller
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x108178b]
goroutine 29 [running]:
github.com/libopenstorage/stork/drivers/volume/portworx.(*portworx).InspectVolume(0xc4203393a0, 0xc4202c84e0, 0x28, 0x1d, 0xc420404f01, 0x0)
	/home/travis/gopath/src/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go:100 +0x22b
github.com/libopenstorage/stork/drivers/volume/portworx.(*portworx).GetPodVolumes(0xc4203393a0, 0xc42055c000, 0x30, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go:194 +0x3f7
github.com/libopenstorage/stork/pkg/monitor.(*Monitor).driverMonitor(0xc42021ef80)
	/home/travis/gopath/src/github.com/libopenstorage/stork/pkg/monitor/monitor.go:91 +0x319
created by github.com/libopenstorage/stork/pkg/monitor.(*Monitor).Start
	/home/travis/gopath/src/github.com/libopenstorage/stork/pkg/monitor/monitor.go:45 +0x12a
```

**What you expected to happen**:
Stork pods should be in running state.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@master0 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by adityadani** [comment]
Complete logs are [here](https://gist.github.com/adityadani/c7ba16b2a1b6812758a2e2549e0b7425)
